// Generated by CoffeeScript 1.6.2
/*
 **
* jQuery Yandex fedbacks Plugin for socialmart.ru
*
* Author: Alexander Berdyshev
*
* Version: 1.0
*
 **
*/


(function() {
  var __slice = [].slice;

  (function($smw2Jq, window1, window) {
    var Smw2;

    return Smw2 = (function() {
      Smw2.prototype.$el = null;

      Smw2.prototype.defaults = {
        title: '',
        serverUrl: 'http://socialmart.ru',
        searchMode: 'splitbylat',
        region: 213,
        cssLinkPath: 'http://socialmart.ru/css/style.css',
        widgetSelectorId: 'smw2',
        modelId: 0,
        limit: 5
      };

      Smw2.prototype.dataCache = {
        name: "",
        offers: []
      };

      Smw2.prototype.log = function(str) {
        console.log(str);
      };

      Smw2.prototype.appendLibraries = function() {
        var self;

        self = this;
        $smw2Jq('head').prepend($smw2Jq('<link/>', {
          'href': self.options.cssLinkPath,
          'rel': 'stylesheet'
        }));
      };

      function Smw2(el, options) {
        this.options = $smw2Jq.extend({}, this.defaults, options);
        this.$el = $smw2Jq(el);
        this.init();
        this.appendLibraries();
        return;
      }

      Smw2.prototype.eventHandlers = {
        redirectClick: function(e) {
          var href, self;

          self = e.data.plugin;
          href = $smw2Jq(this).data('smw2Redirect');
          window.open(href);
        }
      };

      Smw2.prototype.attachEvents = function() {
        var self;

        self = this;
        $smw2Jq('#smw2').on('click', '.smw2__body tr', {
          plugin: self
        }, self.eventHandlers.redirectClick);
      };

      Smw2.prototype.fetchId = function() {
        var selfOpts, url;

        selfOpts = this.options;
        url = "" + selfOpts.serverUrl + "/widget/get/model/?name=" + selfOpts.title + "&jsonp=?";
        return $smw2Jq.ajax({
          'url': url,
          'dataType': 'jsonp'
        });
      };

      Smw2.prototype.fetchPrices = function() {
        var selfOpts, url;

        selfOpts = this.options;
        console.log(this.options.modelId);
        url = "http://socialmart.ru/widget/get/model/prices?model=" + selfOpts.modelId + "&region=" + selfOpts.region + "&jsonp=?";
        return $smw2Jq.ajax({
          'url': url,
          'dataType': 'jsonp'
        });
      };

      Smw2.prototype.fetchDescription = function() {
        var selfOpts, url;

        selfOpts = this.options;
        url = "http://socialmart.ru/widget/get/model/info?model=" + selfOpts.modelId + "&region=" + selfOpts.region + "&jsonp=?";
        return $smw2Jq.ajax({
          'url': url,
          'dataType': 'jsonp'
        });
      };

      Smw2.prototype.fillWidget = function() {
        var html, source, template;

        console.log(this.dataCache);
        source = $smw2Jq("#smw2-template").html();
        template = Handlebars.compile(source);
        html = template(this.dataCache);
        $smw2Jq('#smw2').html(html);
      };

      Smw2.prototype.init = function() {
        var self;

        self = this;
        self.attachEvents();
        self.fetchId().done(function(d) {
          self.options.modelId = d.model_id;
          self.fetchDescription().done(function(d) {
            self.dataCache.name = d.name;
            self.fetchPrices().done(function(d) {
              d.offers.forEach(function(data, index) {
                if (index < self.options.limit) {
                  self.dataCache.offers.push({
                    name: data.name,
                    shopRating: data.shopRating * 20,
                    price: data.price,
                    clickUrl: data.clickUrl
                  });
                }
              });
              self.fillWidget();
            });
          });
        });
      };

      $smw2Jq.fn.extend({
        smw2: function() {
          var args, option;

          option = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
          return this.each(function() {
            var $this, data;

            $this = $smw2Jq(this);
            data = $this.data('smw2');
            if (!data) {
              $this.data('smw2', (data = new Smw2(this, option)));
            }
            if (typeof option === 'string') {
              return data[option].apply(data, args);
            }
          });
        }
      });

      return Smw2;

    })();
  })($smw2Jq, window.jQuery, window);

}).call(this);
